version: '3'

services:

  elsa_bot:
      image: simple_kbqa:latest
      restart: always
      ports:
          - 5000:5000
      volumes:
          - ../data:/opt/chatbot/data
      working_dir: /opt/chatbot
      environment:
          BOT_CHECKPOINT: /opt/chatbot/data/kbqa/elsa/checkpoint
          W2V_WORD2IDX: /opt/chatbot/data/word2vec/embedding.lookup
          W2V_IDX2VEC: /opt/chatbot/data/word2vec/embedding.h5py
