version: '3'

services:

  elsa_bot:
      image: simple_kbqa:latest
      restart: always
      ports:
          - 5000:5000
      volumes:
          - ../data:/opt/chatbot/data
      working_dir: /opt/chatbot
      environment:
          BOT_CHECKPOINT:
          W2V_WORD2IDX:
          W2V_IDX2VEC:
